#include "cube/cube_model.hpp"
#include "cube/cube_normals.hpp"
#include "cube/cube_uv.hpp"
#include "cube/cube_texture.hpp"
#include "cube/cubespec_texture.hpp"

#include "monitor/monitor_model.hpp"
#include "monitor/monitor_normals.hpp"
#include "monitor/monitor_uv.hpp"

#include "plane/plane_model.hpp"
#include "plane/plane_normals.hpp"
#include "plane/plane_uv.hpp"

#include "car/hpp/carcas_model.hpp"
#include "car/hpp/carcas_normals.hpp"
#include "car/hpp/carcas_uv.hpp"

#include "car/hpp/saloon_model.hpp"
#include "car/hpp/saloon_normals.hpp"
#include "car/hpp/saloon_uv.hpp"

#include "car/hpp/stwheel_model.hpp"
#include "car/hpp/stwheel_normals.hpp"
#include "car/hpp/stwheel_uv.hpp"

#include "car/hpp/wheels_model.hpp"
#include "car/hpp/wheels_normals.hpp"
#include "car/hpp/wheels_uv.hpp"

#include "textures/hpp/albedo_texture.hpp"
#include "textures/hpp/spec_texture.hpp"

#include "textures/hpp/dollar_texture.hpp"
#include "textures/hpp/tr1_texture.hpp"
#include "textures/hpp/tr2_texture.hpp"
#include "textures/hpp/tr3_texture.hpp"
#include "textures/hpp/tr4_texture.hpp"
#include "textures/hpp/tr5_texture.hpp"
#include "textures/hpp/tr6_texture.hpp"
#include "textures/hpp/n0_texture.hpp"
#include "textures/hpp/n7_texture.hpp"
#include "textures/hpp/n8_texture.hpp"
#include "textures/hpp/n9_texture.hpp"
#include "textures/hpp/trr_texture.hpp"
#include "textures/hpp/trn_texture.hpp"
#include "textures/hpp/lowfl_texture.hpp"

#include "textures/hpp/l30_texture.hpp"
#include "textures/hpp/l60_texture.hpp"

#include "ways/hpp/waygrass_model.hpp"
#include "ways/hpp/waygrass_normals.hpp"
#include "ways/hpp/waygrass_uv.hpp"

#include "ways/hpp/fence_model.hpp"
#include "ways/hpp/fence_normals.hpp"
#include "ways/hpp/fence_uv.hpp"

#include "ways/hpp/gasstat_model.hpp"
#include "ways/hpp/gasstat_normals.hpp"
#include "ways/hpp/gasstat_uv.hpp"

#include "ways/hpp/mountain_model.hpp"
#include "ways/hpp/mountain_normals.hpp"
#include "ways/hpp/mountain_uv.hpp"

#include "ways/hpp/speedlimit_model.hpp"
#include "ways/hpp/speedlimit_normals.hpp"
#include "ways/hpp/speedlimit_uv.hpp"

#include "ways/hpp/stone_model.hpp"
#include "ways/hpp/stone_normals.hpp"
#include "ways/hpp/stone_uv.hpp"

#include "ways/hpp/tree_model.hpp"
#include "ways/hpp/tree_normals.hpp"
#include "ways/hpp/tree_uv.hpp"

#include "ways/hpp/waystone_model.hpp"
#include "ways/hpp/waystone_normals.hpp"
#include "ways/hpp/waystone_uv.hpp"

#include "textures/hpp/begin_texture.hpp"
#include "textures/hpp/quit_texture.hpp"
#include "textures/hpp/full_texture.hpp"

#include "textures/hpp/icon_texture.hpp"

using namespace std;

const char* vertexShaderCode =
                    "#version 400\n"
                    "layout (location = 0) in vec3 positions;" 
                    "layout (location = 1) in vec3 normals;" 
                    "layout (location = 2) in vec2 uv;" 
                    "uniform mat4 proj;" 
                    "uniform mat4 translate;" 
                    "uniform mat4 xrot;" 
                    "uniform mat4 yrot;" 
                    "uniform mat4 meshm;" 

                    "uniform mat4 sproj[10];" 
                    "uniform mat4 stranslate[10];" 
                    "uniform mat4 sxrot[10];" 
                    "uniform mat4 syrot[10];" 

                    "out vec2 fuv;"
                    "out vec3 fnormals;"
                    "out vec3 fpos;"
                    "out vec4 projlightmat;"
                    "void main() {" 
                    "  gl_Position = proj * xrot * yrot * translate * meshm * vec4(positions, 1.0f);" 
                            "fuv = vec2(uv.x, uv.y+1);"
                            "fnormals = mat3(transpose(inverse(mat4(1.0f)))) * normals;"
                            "fpos = vec3(mat4(1.0f) * vec4(positions, 1.0f));"
                            "projlightmat = sproj[0] * sxrot[0] * syrot[0] * stranslate[0] * meshm * vec4(positions, 1.0f);"
                    "}";

const char* fragmentShaderCode =
                    "#version 400\n" 
                    "uniform sampler2D tex1;"
                    "uniform sampler2D spec1;"
                    "uniform sampler2D shadowMap0;"
                    "uniform vec3 lightsPos[10];"
                    "uniform vec3 lightsCol[10];"
                    "uniform int lightStates[10];"
                    "uniform vec3 viewPos;"
                    "in vec4 projlightmat;"
                    "in vec2 fuv;"
                    "in vec3 fnormals;"
                    "in vec3 fpos;"
                    "layout(location = 0) out vec4 color;"
                    "float shadowMapping(){" 
                    "  vec3 projected = projlightmat.xyz / projlightmat.w;" 
                    "  float shadow = 0.0f;" 
                    "  if(projected.z <= 1.0f){" 
                    "   projected = (projected + 1.0f)/2.0f;" 
                    "   float closestDepth = texture(shadowMap0, projected.xy).r;" 
                    "   float currentDepth = projected.z;" 
                    "   if(currentDepth - 0.0001 > closestDepth){" 
                    "       shadow+=1.0f;" 
                    "   }" 
                    "  }" 
                    "  return shadow;" 
                    "}" 
                    "float phongl(vec3 lightpos){" 
                    "  float ambient = 0.1;" 
                    "  vec3 norm = normalize(fnormals);" 
                    "  vec3 ldir = normalize(lightpos-fpos);" 
                    "  float diffuse = max(dot(norm, ldir), 0.0);" 
                    "  vec3 viewDir = normalize(-viewPos - fpos);" 
                    "  vec3 halfwayDir = normalize(ldir + viewDir);" 
                    "  float spec = pow(max(dot(norm, halfwayDir), 0.0), 16.0) * texture(spec1, fuv).r;" 
                    "  return float((spec + diffuse)*(1.0-shadowMapping()) + ambient);" 
                    "}" 
                    "void main() {" 
                    "  vec3 toOut = phongl(lightsPos[0]) * lightsCol[0] * texture(tex1, fuv).rgb;" 
                    "  color = vec4( toOut, 1.0);" 
                    "}";

const char* fragmentShaderCode2 =
            "#version 400\n" 
                    "precision mediump float;" 
                    "uniform sampler2D tex1;"
                    "uniform sampler2D spec1;"
                    "uniform sampler2D shadowMap0;"
                    "uniform vec3 lightsPos[10];"
                    "in vec4 projlightmat;"
                    "in vec2 fuv;"
                    "in vec3 fnormals;"
                    "layout(location = 0) out vec4 color;"
                    "void main() {" 
                    "  color = vec4(texture(shadowMap0, fuv).rrr, 1.0);" 
                    "}";

const char* vertexuiShaderCode =
                    "#version 400\n"
                    "layout (location = 0) in vec3 positions;" 
                    "layout (location = 1) in vec3 normals;" 
                    "layout (location = 2) in vec2 uv;" 
                    "uniform mat4 proj;" 
                    "uniform mat4 translate;" 
                    "uniform mat4 xrot;" 
                    "uniform mat4 yrot;" 
                    "uniform mat4 meshm;" 

                    "uniform mat4 sproj[10];" 
                    "uniform mat4 stranslate[10];" 
                    "uniform mat4 sxrot[10];" 
                    "uniform mat4 syrot[10];" 

                    "out vec2 fuv;"
                    "out vec3 fnormals;"
                    "out vec3 fpos;"
                    "out vec4 projlightmat;"
                    "void main() {" 
                    "  gl_Position = vec4(positions, 1.0f);" 
                            "fuv = vec2(uv.x, uv.y);"
                    "}";

const char* fragmentuiShaderCode =
                    "#version 400\n" 
                    "uniform sampler2D tex1;"
                    "uniform sampler2D spec1;"
                    "uniform sampler2D shadowMap0;"
                    "uniform vec3 lightsPos[10];"
                    "uniform vec3 lightsCol[10];"
                    "uniform int lightStates[10];"
                    "uniform vec3 viewPos;"
                    "in vec4 projlightmat;"
                    "in vec2 fuv;"
                    "in vec3 fnormals;"
                    "in vec3 fpos;"
                    "layout(location = 0) out vec4 color;"
                    "void main(){"
                    "  color = vec4( texture(tex1, fuv).rgb, 1.0);" 
                    "}";